TARGET_SCREEN_READER = "TARGET_SCREEN_READER"
TARGET_CONTROLLER = "TARGET_CONTROLLER"
DISCONNECT = "DISCONNECT"
ALREADY_CONNECTED = "ALREADY_CONNECTED"

TARGET_WAITING = "TARGET_WAITING"
TARGET_RUNNING = "TARGET_RUNNING"

WATCHER = "WATCHER"
WATCHER_SCREEN_READER = "WATCHER_SCREEN_READER"
WATCHER_CONTROLLER = "WATCHER_CONTROLLER"
SEND_TARGET_LIST = "SEND_TARGET_LIST"
WATCH_BY_CODE = "WATCH_BY_CODE"
STOP_WATCHING = "STOP_WATCHING"
CONTROL_KEYBOARD = "CONTROL_KEYBOARD"
CONTROL_MOUSE = "CONTROL_MOUSE"


from enum import Enum
class ImageSendModes(Enum):
    DIRECT_JPG = 0  # send the whole new image
    DIFF = 1        # subtract one image from another and send diff
    CHANGES = 2     # send the changed areas of image
