IMG_FORMAT = "JPEG"
SERVER_ADDRESS = "127.0.0.1"
SERVER_PORT = 11419

TARGET_SCREEN_READER = "TARGET_SCREEN_READER"
TARGET_CONTROLLER = "TARGET_CONTROLLER"
DISCONNECT = "DISCONNECT"
ALREADY_CONNECTED = "ALREADY_CONNECTED"

TARGET_WAITING = "TARGET_WAITING"
TARGET_RUNNING = "TARGET_RUNNING"

WATCHER = "WATCHER"
WATCHER_SCREEN_READER = "WATCHER_SCREEN_READER"
WATCHER_CONTROLLER = "WATCHER_CONTROLLER"
SEND_TARGET_LIST = "SEND_TARGET_LIST"
WATCH_BY_CODE = "WATCH_BY_CODE"
STOP_WATCHING = "STOP_WATCHING"